# fly.toml app configuration file generated for supabase-pipeline on 2024-07-30T09:38:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supabase-pipeline'
primary_region = 'ams'

[build]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = "8080"
    handlers = ["http"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
